### PR TITLE
fix empty instance get

### LINKED ISSUE #434: Test dialog break test scores view
from the implementation done for https://github.com/MetaCell/geppetto-scidash/pull/427 this broke the test score view due a condition check per instance.

### PR DESCRIPTION
**Pull request by ddelpiano**
fix #434

### CODE REVIEW

File: components/griddle-columns/test-detail-link-column/TestDetailLinkColumn.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ export default class TestDetailLinkColumn extends React.Component {
               cursor: "pointer",
             }}
           >
-            {this.props.testInstanceObject !== undefined
+            {this.props.testInstanceObject !== undefined && this.props.testInstanceObject !== " "
```
Comment (zsinnema) [inline components/griddle-columns/test-detail-link-column/TestDetailLinkColumn.js:54]: can testinstanceobject also contain multiple spaces?
then I would suggest 
`this.props.testInstanceObject !== undefined && this.props.testInstanceObject.trim()`

**Comment by ddelpiano** [comment]
@zsinnema could you review this please? I am merging it so I can refresh the CD and get a working instance and let @gidili do some testing as well since he does not have local deployment, if this is not fine we can rework it with another PR. Thx!

**Review by zsinnema — COMMENTED** [review]
lgtm
